apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: va-ui-app
  namespace: default
  labels:
    name: va-ui-app
    app: va-ui-app
spec:
  componentKinds:
    - group: apps
      kind: Deployment
  descriptor: {}
  selector:
    matchLabels:
      app: va-ui-app
---
apiVersion: mcm.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: va-ui-deployment
  namespace: default
  labels:
    name: va-ui-deployment
    app: va-ui-app
    placementPolicy: va-ui-deployment
    serviceKind: ApplicationService
spec:
  deployer:
    helm:
      namespace: default
      chartName: iva-ui
      chartURL: >-
        https://raw.githubusercontent.com/srinivas511/inference-server-repo/master/iva-ui-0.1.0.tgz
      repository: inference-github-repo
    kind: helm
---
apiVersion: mcm.ibm.com/v1alpha1
kind: PlacementPolicy
metadata:
  name: va-ui-deployment
  namespace: default
  labels:
    name: va-ui-deployment
    app: va-ui-app
spec:
  clusterLabels:
    matchLabels:
      datacenter: us-east
  clusterReplicas: 2
  resourceHint: {}
  resourceSelector: {}
---
apiVersion: mcm.ibm.com/v1alpha1
kind: PlacementBinding
metadata:
  name: va-ui-deployment-binding
  namespace: default
  labels:
    name: va-ui-deployment-binding
    placementPolicy: va-ui-deployment
placementRef:
  name: va-ui-deployment
  apiGroup: mcm.ibm.com
  kind: PlacementPolicy
subjects:
  - name: va-ui-deployment
    apiGroup: mcm.ibm.com
    kind: Deployable
---
apiVersion: mcm.ibm.com/v1alpha1
kind: ApplicationRelationship
metadata:
  name: va-ui-deployment-apprelation
  namespace: default
  labels:
    app: va-ui-app
    destinationKind: Deployable
    destinationName: va-ui-deployment
    sourceKind: Application
    sourceName: va-ui-app
spec:
  destination:
    name: va-ui-deployment
    kind: Deployable
  source:
    name: va-ui-app
    kind: Application
  type: contains