apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: hardhat-app
  namespace: default
  generation: 2
  labels:
    name: hardhat-app
    app: hardhat-app
spec:
  componentKinds:
    - group: apps
      kind: Deployment
  descriptor: {}
  selector:
    matchLabels:
      app: hardhat-app
---
apiVersion: mcm.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: inference
  namespace: default
  labels:
    name: inference
    app: hardhat-app
    placementPolicy: inference
    serviceKind: ApplicationService
spec:
  deployer:
    helm:
      namespace: default
      chartName: inference
      chartURL: >-
        https://raw.githubusercontent.com/srinivas511/inference-server-repo/master/inference-0.0.8.tgz
      repository: inference-github-repo
    kind: helm
---
apiVersion: mcm.ibm.com/v1alpha1
kind: PlacementPolicy
metadata:
  name: inference
  namespace: default
  labels:
    name: inference
    app: hardhat-app
spec:
  clusterLabels:
    matchLabels:
      name: cobalt-ibm
  clusterReplicas: 1
  resourceHint:
    order: desc
    type: GPU
  resourceSelector: {}
---
apiVersion: mcm.ibm.com/v1alpha1
kind: PlacementPolicy
metadata:
  name: inference-local
  namespace: default
  labels:
    name: inference-local
    app: hardhat-app
spec:
  clusterLabels:
    matchLabels:
      name: local-cluster
  clusterReplicas: 1
  resourceHint:
    order: desc
    type: GPU
  resourceSelector: {}
---
apiVersion: mcm.ibm.com/v1alpha1
kind: PlacementBinding
metadata:
  name: inference-binding
  namespace: default
  labels:
    name: inference-binding
    placementPolicy: inference
placementRef:
  name: inference
  apiGroup: mcm.ibm.com
  kind: PlacementPolicy
subjects:
  - name: inference
    apiGroup: mcm.ibm.com
    kind: Deployable
---
apiVersion: mcm.ibm.com/v1alpha1
kind: PlacementBinding
metadata:
  name: inference-local-binding
  namespace: default
  labels:
    name: inference-local-binding
    placementPolicy: inference-local
placementRef:
  name: inference-local
  apiGroup: mcm.ibm.com
  kind: PlacementPolicy
subjects:
  - name: inference
    apiGroup: mcm.ibm.com
    kind: Deployable
---
apiVersion: mcm.ibm.com/v1alpha1
kind: ApplicationRelationship
metadata:
  name: inference-apprelation
  namespace: default
  labels:
    app: hardhat-app
    destinationKind: Deployable
    destinationName: inference
    sourceKind: Application
    sourceName: hardhat-app
spec:
  destination:
    name: inference
    kind: Deployable
  source:
    name: hardhat-app
    kind: Application
  type: contains
---
apiVersion: mcm.ibm.com/v1alpha1
kind: ApplicationRelationship
metadata:
  name: inference-local-apprelation
  namespace: default
  labels:
    app: hardhat-app
    destinationKind: Deployable
    destinationName: inference
    sourceKind: Application
    sourceName: hardhat-app
spec:
  destination:
    name: inference
    kind: Deployable
  source:
    name: hardhat-app
    kind: Application
  type: contains